### ISSUE TITLE
SelectionItem and SelectionItemPattern doesn't work as expected.

### ISSUE THREAD

**Issue by 1504168** [Descolada/UIAutomation#49] opened 2024-02-27 10:36 UTC
Here is how to reproduce it:

1. Download this file and open it in Excel. https://drive.google.com/file/d/1d_Qkm9wZWxhzP_-PMd0LBDCmgETpTDK3/view?usp=sharing

2. Click on the Open Form Button. 
![image](https://github.com/Descolada/UIAutomation/assets/31016570/d23bcd47-cc3c-49d8-ad3e-e667cb90e903)

3. It will open this form. Now keep this form open. 
![image](https://github.com/Descolada/UIAutomation/assets/31016570/b62508a6-44fa-4384-9f55-4d0dfffeb30a)

4. Now Run "UIATreeInspector.ahk"

5. Select like below image for that particular UI.
![image](https://github.com/Descolada/UIAutomation/assets/31016570/535db8be-31ae-41e8-add3-e750c3886fdd)
7. Select any item from these two list and double click on the select()

8. You will get an error like this. 
![image](https://github.com/Descolada/UIAutomation/assets/31016570/ffe62beb-482b-4d82-9b9d-3b5b8041c49c)

Let me know if I can explain any other things.

**Comment by Descolada** [comment] 2024-02-27 18:02
I am able to reproduce this with UIA_Interface, UIA v2, the Acc library, and also with Accessibility Insights. This means the problem is most likely in how Excel implements IAccessible/Acc (the old version of UIAutomation) for that particular window. Window spy reports the control name for the listbox as "F3 Server 0e3f00002" which is unusual as well, as it should be something like "Listbox1", so it's some kind of special implementation by Excel. It appears `Element.LegacyIAccessiblePattern.DoDefaultAction()` works IF the listbox is already selected, but it can't select multiple items in the second listbox. `Element.ControlClick()` seems to select single items as well, but selecting multiple items also did not work. I could select multiple items with
```
Send {Ctrl down}
Element.Click("left")
Send {Ctrl up}
```
but of course the elements need to be visible (that is, not scrolled out of view) for this to work.

I'm closing this because unfortunately there isn't a fix possible from this libraries side.

**Closed by Descolada** 2024-02-27 18:02 UTC

**Comment by 1504168** [comment] 2024-02-28 04:31
Element.Click("left") seems selecting the wrong item in the list.

**Comment by Descolada** [comment] 2024-02-29 07:01
Works fine here...
```
#Requires AutoHotkey v1 
#include <UIA_Interface>

UIA := UIA_Interface()
winTitle := "Sample UI to showcase UIA Select Issue ahk_exe EXCEL.exe"
WinActivate %winTitle%
WinWaitActive %winTitle%
winEl := UIA.ElementFromHandle(winTitle)
winEl.FindFirstByNameAndType("Badminton", "ListItem").Click("left")
Send {Ctrl down}
winEl.FindFirstByNameAndType("Football", "ListItem").Click("left")
Send {Ctrl up}
winEl.FindFirstByNameAndType("Male", "ListItem").Click("left")
ExitApp
```
![ExcelTest](https://github.com/Descolada/UIAutomation/assets/16986957/4a763fa4-bf00-43a0-97ea-7d5d5336ee87)
